spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Krishiv@05
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: Coupon-Service  
    

server:
  port: 9990
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url:
     defaultZone: http://localhost:8761/eureka
      

  

    
 